const fs = require('fs');
let html = fs.readFileSync('cctv24-worship.html', 'utf8');

// We want to remove the gold shimmer line on the bottom bar.
// That is generated by .cinema-bar-bottom::after

const searchStr = `        .cinema-bar-bottom::after {
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            height: 1px;
            background: linear-gradient(
                90deg,
                transparent 0%,
                rgba(212, 175, 55, 0.5) 25%,
                rgba(255, 215, 100, 0.9) 50%,
                rgba(212, 175, 55, 0.5) 75%,
                transparent 100%
            );
            animation: gold-shimmer 4s ease-in-out infinite alternate;
        }`;

if (html.includes(searchStr)) {
    html = html.replace(searchStr, '');
    fs.writeFileSync('cctv24-worship.html', html);
    console.log("Bottom gold shimmer removed.");
} else {
    // try to match with different line endings
    const normalizedHtml = html.replace(/\r\n/g, '\n');
    const normalizedSearch = searchStr.replace(/\r\n/g, '\n');
    if (normalizedHtml.includes(normalizedSearch)) {
        html = normalizedHtml.replace(normalizedSearch, '');
        fs.writeFileSync('cctv24-worship.html', html);
        console.log("Bottom gold shimmer removed (normalized).");
    } else {
        console.log("Could not find the bottom gold shimmer CSS.");
    }
}
